name             'my_first_cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks/echo-is-everything'
long_description 'Installs/Configures cookbooks/echo-is-everything'
version          '0.1.0'
