bash "echo hi"


file 'Fix iptables' do
  path '/etc/iptables/rules.v4'
  content <<-EOT
# Generated by iptables-save v1.4.21 on Tue Jun 14 15:41:38 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Tue Jun 14 15:41:38 2016
EOT
  notifies :restart, 'service[iptables-persistent]', :immediately
end

file 'Fix routes' do
  path '/etc/network/if-up.d/dns-router'
  action :delete
  notifies :run, 'bash[fix routes 8.8.8.8]', :immediately
  notifies :run, 'bash[fix routes 8.8.4.4]', :immediately
  notifies :run, 'bash[fix routes 10.0.2.3]', :immediately
  notifies :run, 'bash[fix routes default]', :immediately
end

file 'Fix dns' do
  path '/etc/network/if-up.d/dns-scrambler'
  action :delete
  notifies :run, 'bash[fix dns iptables]', :immediately
end

service 'iptables-persistent' do
  supports :start => true, :restart => true, :reload => true
  action :nothing
end

bash 'fix dns iptables' do
  code <<-EOD
iptables -t nat -F
  EOD
  only_if 'iptables -t nat -L -n  -v | grep 8\.8\.8\.8'
  action :nothing
end


bash 'fix routes 8.8.8.8' do
  code <<-EOD
ip route del 8.8.8.8
  EOD
  only_if 'ip route show | grep 8\.8\.8\.8'
  action :nothing
end

bash 'fix routes 8.8.4.4' do
  code <<-EOD
ip route del 8.8.4.4
  EOD
  only_if 'ip route show | grep 8\.8\.4\.4'
  action :nothing
end

bash 'fix routes 10.0.2.3' do
  code <<-EOD
ip route del 10.0.2.3
  EOD
  only_if 'ip route show | grep 10\.0\.2\.3'
  action :nothing
end


bash 'fix routes default' do
  code <<-EOD
ip route add default via 10.0.2.2 dev eth0
  EOD
  not_if 'ip route show | grep default'
  action :nothing
end


